### ISSUE TITLE
Doesn't work on iPhone 7+

### ISSUE THREAD

**Issue by MihaelIsaev** [robinsenior/RSMaskedLabel#3]
Hey, please help me to fix this error

```
CGImageMaskCreate: invalid mask bits/component: 16.
```

It happens on line #70 in RSMaskedLabel.m

this error appears only on iPhone 7+ :(

**Comment by robinsenior** [comment]
@MihaelIsaev sorry, just noticed this. Is this an issue with the 7+ or with iOS 10?

**Comment by MihaelIsaev** [comment]
@robinsenior This issue is for iPhone 7+ on iOS10.
On iPhone 7, iPhone 6+, iPhone 6, iPhone SE, iPhone 5 on iOS 10 it works fine.
So it's an issue for iPhone 7+ only.

**Comment by xyfqldy** [comment]
Crash on iPhone 7 Plus at code `CFRelease(image)` error:`invalid mask bits/component: 16.`

**Comment by robinsenior** [comment]
I can't get it to crash on the simulator; I'll try to track down a 7+ device to test it on.

**Comment by robinsenior** [comment]
Looks like it has to do with Wide Color support on the 7+: http://stackoverflow.com/questions/41972877/bitmap-context-for-wide-color-range

**Comment by vesterbaek** [comment]
You can fix it by using a new, temporary bitmap context. Swift example below:
```swift
        // Create a new context that we can render the label text into
        // This is required to ensure we render into at 8 bits per component context since this is the
        // max supported by CGImageMaskCreate used below
        // iPhone 7+ (and new iPad pros?) are now using 16 bit per component
        // From UIGraphicsBeginImageContextWithOptions doc: "The format for the bitmap is a ARGB 32-bit integer pixel format using host-byte order."
        UIGraphicsBeginImageContextWithOptions(rect.size, false, 0.0)
        super.drawTextInRect(UIEdgeInsetsInsetRect(rect, textInset))
        var context = UIGraphicsGetCurrentContext()!
        
        // Create a mask from the normally rendered text
        let image = CGBitmapContextCreateImage(context)!
        
        // We got our image, release the image context
        UIGraphicsEndImageContext()
```

**Comment by robinsenior** [comment]
Patch is up here, can someone please take a look? https://github.com/robinsenior/RSMaskedLabel/pull/4

Thanks for your help, @vesterbaek!
